### ISSUE TITLE
Migration steps with same name are erroneously skipped

### ISSUE THREAD

**Issue by asg017** [simonw/sqlite-migrate#11]
Discovered when I had two separate migrations with different `migration_set` names but the same step name. 

The first migration: 

```python
from sqlite_migrate import Migrations

m1 = Migrations("m1")

@m1()
def m001_init(db):
    pass
```

The second:

```
from sqlite_migrate import Migrations
m2 = Migrations("m2")

@m2()
def m001_init(db):
    pass
```

The `m1.m001_init()` step runs successfully, but `m2.m001_init()` is skipped. This is because they share the same step name `m001_init`, but they should have a different namespace anyway.

Caused by this, I think: https://github.com/simonw/sqlite-migrate/blob/82f3459635b495ae909e0a744ad4326ef94dbe26/sqlite_migrate/__init__.py#L51

**Comment by simonw** [comment]
Ouch, there's another problem here:

https://github.com/simonw/sqlite-migrate/blob/82f3459635b495ae909e0a744ad4326ef94dbe26/sqlite_migrate/__init__.py#L84-L97

The primary key on `_sqlite_migrations` is on `name` - but clearly it should be. compound primary key on (`migration_set`, `name`) instead - otherwise you can't have two migration sets with duplicate names.

**Comment by simonw** [comment]
Frustrating that we don't have migrations for the `_sqlite_migrations` table itself! I'm going to have to write code that knows how to upgrade that table by introspecting if it has the correct primary key.

**Comment by simonw** [comment]
I manually tested it against a file that had previously been migrated.

Before it had the old single primary key:
```
$ sqlite-utils schema creatures.db 
CREATE TABLE [_sqlite_migrations] (
   [migration_set] TEXT,
   [name] TEXT PRIMARY KEY,
   [applied_at] TEXT
);
CREATE TABLE [creatures] (
   [id] INTEGER PRIMARY KEY,
   [name] TEXT,
   [species] TEXT
, [weight] FLOAT);
$ sqlite-utils migrate creatures.db
```
Now it has the new primary key scheme:
```
$ sqlite-utils schema creatures.db 
CREATE TABLE "_sqlite_migrations" (
   [migration_set] TEXT,
   [name] TEXT,
   [applied_at] TEXT,
   PRIMARY KEY ([migration_set], [name])
);
CREATE TABLE "creatures" (
   [id] INTEGER PRIMARY KEY,
   [name] TEXT,
   [species] TEXT,
   [weight] FLOAT,
   [age] INTEGER,
   [shoe_size] INTEGER
);
```
Running it a second time makes no changes:
```
$ sqlite-utils migrate creatures.db
$ sqlite-utils schema creatures.db 
CREATE TABLE "_sqlite_migrations" (
   [migration_set] TEXT,
   [name] TEXT,
   [applied_at] TEXT,
   PRIMARY KEY ([migration_set], [name])
);
CREATE TABLE "creatures" (
   [id] INTEGER PRIMARY KEY,
   [name] TEXT,
   [species] TEXT,
   [weight] FLOAT,
   [age] INTEGER,
   [shoe_size] INTEGER
);
```
